import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
import NavBar from "@/components/nav-bar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const direction = locale === "ar" ? "rtl" : "ltr";
  return (
    <html
      lang={locale}
      dir={direction}
      className="dark h-full"
      suppressHydrationWarning
    >
      <body
        className={cn(
          "h-screen bg-background font-sans antialiased",
          inter.variable,
        )}
      >
        <div className="flex flex-col">
          <NextIntlClientProvider>
            <NavBar></NavBar>
            {children}
          </NextIntlClientProvider>
        </div>
      </body>
    </html>
  );
}
